services:
  zebra_day:
    container_name: zebra_day
    build: .
    network_mode: host # can set top your own network as needed
    # Add this if not using host mode
    #ports:
    #  - "8118:8118"
    volumes:
      - ./etc:/app/zebra_day/etc
      - ./logs:/app/zebra_day/logs
    command: zday_start
